## Chapter 3
Training Neural Networks resolves around following concepts. 
1. Low level tensor manipulatiom
2. High level deep learning concepts


In [1]:
import tensorflow as tf
import numpy as np

**Here are some random tensors where ones, zeros and random tensor creation using normal distribution.**

In [2]:
x = tf.ones((2, 2))
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [3]:
x = tf.zeros((2, 2))
print(x)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [4]:
x = tf.random.normal((2,2), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.07926796 -0.34862918]
 [-0.33645108  0.94182587]], shape=(2, 2), dtype=float32)


**The difference between tensorflow and numpy is that tensors are constants and cannot be re-assigned**

In [6]:
x = tf.ones((2, 2))
x[0,0] = 3

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

**As ML models' tensors need to be updated. Therefore, tensorflow variables is the tensor creation machenism for creating tensors that are changable.**

In [9]:
x = tf.Variable(x)
print(x)
x = tf.Variable(initial_value=tf.random.normal((2,2)))
print(x)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 1.],
       [1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.86023116, -1.7122514 ],
       [ 0.97283703, -0.9512761 ]], dtype=float32)>


**x.assign_add() and x.assign_sub() are equilent for += and -= in tensors.**

In [10]:
x.assign_add(tf.ones((2,2)))
print(x)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.8602312 , -0.7122514 ],
       [ 1.972837  ,  0.04872388]], dtype=float32)>


**Doing calculations with tensorflow**

In [20]:
a = tf.constant([[1., 2.], [3., 4.]])
print(a)

b = tf.square(a)
print(b)

c = tf.sqrt(a)
print(c)

d = b + c
print(d)

e = tf.matmul(a, b)
print(e)

e *= d
print(e)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.        1.4142135]
 [1.7320508 2.       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 2.         5.4142137]
 [10.732051  18.       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 36.]
 [39. 76.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[  38.      194.9117]
 [ 418.55   1368.    ]], shape=(2, 2), dtype=float32)


**Moreover numpy arrays cannot give the gradient unlike the tensors where you can use GradientTape in order to find the gradient**

In [47]:
input_var = tf.Variable(initial_value=tf.random.normal(shape=(2, 2)))
with tf.GradientTape() as tape:
    results = tf.square(input_var)
gradient = tape.gradient(results, input_var)
print(gradient)

tf.Tensor(
[[-2.4128745  -0.00935973]
 [-0.38748494 -2.0044682 ]], shape=(2, 2), dtype=float32)
